name: "redhill"
version: "1.0.0"
dbt-cloud:
    project-id: 70471823558957
config-version: 2

profile: "semantic"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  redhill:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +database: REIGATE_MESH
      +schema: STAGING
      +materialized: table
    raw_vault:
      +database: REIGATE_MESH
      +schema: RAW_VAULT
      +materialized: incremental
      +on_schema_change: 'append_new_columns'
      hubs:
        +tags: ['hub']
      links:
        +database: REIGATE_MESH
        +schema: RAW_VAULT
        +tags: ['link']
      satellites:
        +database: REIGATE_MESH
        +schema: RAW_VAULT
        +tags: ['satellite']