CREATE DATABASE REIGATE_MESH;
CREATE SCHEMA REIGATE_MESH.STAGING;
CREATE SCHEMA REIGATE_MESH.RAW_VAULT;
CREATE SCHEMA REIGATE_MESH.BUSINESS_VAULT;
CREATE SCHEMA REIGATE_MESH.INFORMATION_MART;
CREATE SCHEMA REIGATE_MESH.BASE;

DROP TABLE CUSTOMER;
DROP TABLE LINEITEM;
DROP TABLE NATION;
DROP TABLE ORDERS;
DROP TABLE PART;
DROP TABLE PARTSUPP;
DROP TABLE REGION;
DROP TABLE SUPPLIER;

DROP TABLE STG_CUSTOMER;
DROP TABLE STG_LINEITEM;
DROP TABLE STG_NATION;
DROP TABLE STG_ORDERS;
DROP TABLE STG_PART;
DROP TABLE STG_PARTSUPP;
DROP TABLE STG_REGION;
DROP TABLE STG_SUPPLIER;

DROP SCHEMA IF EXISTS REDHILL.STAGING;
DROP SCHEMA IF EXISTS PUBLIC_BASE;
DROP SCHEMA IF EXISTS PUBLIC_CONSUMABLE;

DROP SCHEMA IF EXISTS PUBLIC_PUBLIC;
DROP SCHEMA IF EXISTS PUBLIC_BASE;
DROP SCHEMA IF EXISTS PUBLIC_CONSUMABLE;

CREATE SCHEMA STAGING;


CREATE OR REPLACE TABLE CUSTOMER  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;
CREATE OR REPLACE TABLE LINEITEM  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;
CREATE OR REPLACE TABLE NATION    AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;
CREATE OR REPLACE TABLE ORDERS    AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;
CREATE OR REPLACE TABLE PART      AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;
CREATE OR REPLACE TABLE PARTSUPP  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP;
CREATE OR REPLACE TABLE REGION    AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION;
CREATE OR REPLACE TABLE SUPPLIER  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER;

CREATE SCHEMA BASE;

CREATE SCHEMA CONSUMABLE;

SHOW PRIMARY KEYS IN SCHEMA REIGATE_MESH.RAW_VAULT;

DROP TABLE IF EXISTS REIGATE_MESH.RAW_VAULT.link_customer_nation
